# This yaml evolves with the progress of the PanDA deployment

includeConfigs:
- ${CTRL_BPS_PANDA_DIR}/config/bps_panda.yaml

project: dev
campaign: quick
computeCloud: US
computeSite: SLAC
requestMemory: 2048
# PanDA does the scheduling based on memory request

setupLSSTEnv: >
  source /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/{LSST_VERSION}/loadLSST.bash;
  pwd; ls -al;
  setup lsst_distrib;

# To override the IDF runnerCommand. It can be dropped when a universal runnerCommand is available in bps_panda.yaml
runnerCommand: >
  unset PYTHONPATH;
  {setupLSSTEnv}
  python3 ${CTRL_BPS_PANDA_DIR}/python/lsst/ctrl/bps/panda/edgenode/cmd_line_decoder.py _cmd_line_ & pJob=$!;
  prmon -i 5
  -f memory_monitor_output.txt
  -j memory_monitor_summary.json
  -p $pJob & mJob=$!;
  wait $pJob;
  retStat=$?;
  wait $mJob;
  rm -fr EXEC_REPO-*;
  exit $retStat

payload:
  s3EndpointUrl: "https://storage.googleapis.com"
  butlerConfig: /sdf/group/rubin/repo/main
  payloadFolder: payload
  fileDistributionEndPoint: "file:///sdf/group/rubin/sandbox/{operator}/panda_cache_box/{payloadFolder}/{uniqProcName}/"

# Specify memory request for executionButler, pipetaskInit and forcedPhotCoadd, placeholder for now
executionButler:
  requestMemory: 7000
  queue: "SLAC_Rubin_Merge"

pipetask:
  pipetaskInit:
    requestMemory: 4000

  forcedPhotCoadd:
    requestMemory: 4000
