includeConfigs:
- ${CTRL_BPS_PANDA_DIR}/config/bps_panda.yaml


project: dev
campaign: quick
computeCloud: LSST
computeSite: LSST
pipelineYaml: "${OBS_LSST_DIR}/pipelines/imsim/DRP.yaml#step1"

payload:
  butlerConfig: s3://butler-us-central1-panda-dev/dc2/butler-external.yaml

# Job environment setup
custom_lsst_setup: ""
setupLSSTEnv: >
  source /opt/lsst/software/stack/loadLSST.bash;
  setup lsst_distrib;
  {custom_lsst_setup}

# lsst Docker image location in GAR (Google Artifact Registry)
# Must end with slash. Override with empty string to use images from the Docker hub instead.
dockerImageLocation: "us-central1-docker.pkg.dev/panda-dev-1a74/"
payloadFolder: payload
fileDistributionEndPoint: "s3://butler-us-central1-panda-dev/dc2/{payloadFolder}/{uniqProcName}/"
s3EndpointUrl: "https://storage.googleapis.com"
jobLogDir: "/tmp/panda/${PANDAID}"
jobInitDir: "/tmp"
jobContainer: >
  logFile=${logDir}/${REALTIME_LOGFILES};
  touch ${logFile};
  chmod ugo+w ${logFile}; ln -s ${logFile} ./;
  docker run
  --rm
  -v ${logDir}:${logDir}
  -v ${logFile}:/tmp/${REALTIME_LOGFILES}
  --network host
  --privileged
  --env AWS_ACCESS_KEY_ID=$(</credentials/AWS_ACCESS_KEY_ID)
  --env AWS_SECRET_ACCESS_KEY=$(</credentials/AWS_SECRET_ACCESS_KEY)
  --env PGPASSWORD=$(</credentials/PGPASSWORD)
  --env S3_ENDPOINT_URL=${S3_ENDPOINT_URL} {sw_image}
  /bin/bash -c "{payloadCommand}" >&2;

jobCleanup: ""

# IDF is configured with many PanDA queues
# non-preemption is currently not a feature currently
# matched when selecting destination queue automatically.
executionButler:
  queue: "DOMA_LSST_GOOGLE_MERGE"

pipetask:
  forcedPhotCoadd:
    queue: "DOMA_LSST_GOOGLE_TEST_HIMEM_NON_PREEMPT"
